[project]
name = "dagster-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.11.7",
    "dagster-webserver>=1.11.7",
    "pandas>=2.3.2",
]
